export const LABELS = {
  sources: {
    'hermes': 'Hermes 技能库',
    'skills': '技能中心',
    'project-runbook': '项目文档',
    'mcp-config': 'MCP 配置',
    'mcp': 'MCP 工具',
  },
  editors: {
    'Hermes Agent': 'Hermes 代理',
    'Skills Hub': '技能中心',
    'Project Docs': '项目文档',
    'MCP': 'MCP',
    'MCP Hub': 'MCP 中心',
  },
  kinds: {
    'skill': '技能',
    'runbook': '手册',
    'config': '配置',
    'mcp-tool': 'MCP 工具',
    'mcp': 'MCP',
  },
  categories: {
    'devops': '云原生运维',
    'mlops': '机器学习运维',
    'software-development': '软件开发',
    'creative': '创意工具',
    'productivity': '生产力工具',
    'research': '研究',
    'apple': 'Apple 生态',
    'media': '媒体处理',
    'gaming': '游戏',
    'red-teaming': '红队测试',
    'github': 'GitHub',
    'email': '邮件',
    'leisure': '休闲娱乐',
    'smart-home': '智能家居',
    'social-media': '社交媒体',
    'mcp': 'MCP 协议',
    'note-taking': '笔记',
    'huhaa-myskills': 'HuHaa AI 助手',
    'autonomous-ai-agents': '自主 AI 代理',
    'kanban': '看板',
    'eslint': 'ESLint',
  },
  brands: {
    'GitHub': 'GitHub',
    'OpenAI': 'OpenAI',
    'Anthropic': 'Anthropic',
    'Apple': 'Apple',
    'Docker': 'Docker',
    'HuggingFace': 'Hugging Face',
    'Claude Code': 'Claude Code',
    'Suno': 'Suno',
    'Kubernetes': 'Kubernetes',
    'Telegram': 'Telegram',
    'Cloudflare': 'Cloudflare',
    'Modal': 'Modal',
    'Linear': 'Linear',
    'Hermes': 'Hermes',
  }
};
